########
####
#
#
#                               Heu-MCHC
#
# A fast and accurate heuristic algorithm for the haplotype inference
# problem on pedigree data with recombinations and mutations
#
# Copyright (C) 2009,2010,2011  Yuri PIROLA
#
# Distributed under the terms of the GNU General Public License (GPL)
#
#
# This file is part of Heu-MCHC.
#
# Heu-MCHC is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Heu-MCHC is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Heu-MCHC.  If not, see <http://www.gnu.org/licenses/>.
#
####
#
# Definition for the GNU Compiler Collection
#
########

CC=gcc
CXX=g++

#####################
# Common compiler options
#
OPTB= -Wall -Wextra -pedantic -g
OPTBCC=$(OPTB) -std=gnu99
OPTBCXX=$(OPTB) -std=gnu++0x -Wno-variadic-macros -Wno-deprecated
#####################

#####################
# Compiler options for production code
#
ifeq ($(STATUS), production)
OPTP=-march=native -mfpmath=sse -msse2 -O3
#OPTP=-O3 -march=native -mmmx -msse -msse2 -ftree-vectorize -funroll-loops -findirect-inlining -ftree-switch-conversion -floop-interchange -floop-strip-mine -floop-block -Wall -pipe -fno-math-errno -funsafe-math-optimizations -fno-rounding-math -fno-signaling-nans -fcx-limited-range
endif
#####################

#####################
# Compiler options for verbose code
#
ifeq ($(STATUS), verbose)
OPTP=-O2
endif
#####################

#####################
# Compiler options for debugging code
#
ifeq ($(STATUS), debug)
OPTD=-O0
endif
#####################

#####################
# Compiler options for profiling code
#
#
ifeq ($(PROF), yes)
OPTPROF=-pg -fprofile-arcs
else
OPTPROF=
endif
#####################

